### ISSUE TITLE
Pre-select current game mode, preset and map

### ISSUE THREAD

**Issue by Roemer** [peterekepeter/ut99-mves#4]
It would be cool if the mutator could pre-select the current game mode, preset and map. Then a user can just select a new map and keep the rest the same.

**Comment by peterekepeter** [comment]
It's true that currently selecting a map is a lot of work and the UI is overwhelming, that's some of the feedback I've been getting and is consistent with what I see in servers where players wait for the first vote and just double down on that vote instead of searching for another map or mode.

Your suggestion can help with this problem. It would reduce the number of clicks required to vote something.

Alternatively what I've been thinking is to persist the selection that the user made in the map-vote, so if you voted a specific map but it didn't win it would be easier to vote it again.


I'm trying to find a way to fuse the two, maybe as a fallback:

1. if user made a selection then pre-select last selection that the user made
2. if 1. fails and if current mode/map was not default map then pre-select current mode
3. else show empty state with nothing selected

What do you think?

**Comment by Roemer** [comment]
I like the idea of pre-selecting the last selection of the user and the fallback of the current settings. Sounds reasonable. As an addition to this maybe you could fit a button somewhere which says "Select current" or something like that. So that if the user had something selected on the last vote but somehow liked the current one, he can still immediately go to the current mode/map.

Other than that, pretty cool work. I hope you don't mind I added your mapvote as default in my UT99 Server Docker image https://github.com/Roemer/ut99-server as I tested a LOT of mapvotes and yours somehow worked the best and was easily configurable.

**Comment by peterekepeter** [comment]
Sounds good, I'll see if it can be done without overloading the UI too much. But don't expect this soon, I didn't have much time lately to make changes on it. There are also few more pressing issues right now.

Thanks! Feel free to do whatever you want with it. I just picked it up one day and started fixing bugs. But its nice to hear that it works well enough for you to bundle it into a docker image. This mapvote is the work of multiple people across long period of time, it has lot of legacy and bugs, but I try to make it have at least good defaults out of the box.

**Comment by peterekepeter** [comment]
The new release MVE2h contains this improvement. Its not exactly as described here. 

https://github.com/peterekepeter/ut99-mves/releases/tag/MVE2h

Let me know your thoughts after you use it for a while.
